# Generated by Django 2.2.6 on 2020-10-09 10:25

from django.db import migrations
from bastion.utils.init_script import init_default_group


def run_init(apps, schema_editor):
    pass
    # init_default_group()


class Migration(migrations.Migration):

    dependencies = [
        ('bastion', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run_init)
    ]