# Generated by Django 2.2.6 on 2020-10-09 10:25

from django.db import migrations

from bastion.utils.init_command_script import init_command


def run_init(apps, schema_editor):
    init_command()


class Migration(migrations.Migration):

    dependencies = [
        ('bastion', '0002_init_script'),
    ]

    operations = [
        migrations.RunPython(run_init)
    ]