# Generated by Django 2.2.6 on 2020-10-09 10:25

from django.db import migrations

from bastion.utils.create_iam import init_system_to_iam


def run_init(apps, schema_editor):
    init_system_to_iam()


class Migration(migrations.Migration):

    dependencies = [
        ('bastion', '0003_init_command_script'),
    ]

    operations = [
        migrations.RunPython(run_init)
    ]