# Generated by Django 2.2.6 on 2021-11-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bastion', '0007_init_iam_action_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroupmodel',
            name='group_type',
            field=models.CharField(choices=[('host', '主机资源'), ('database', '数据库')], default='host', max_length=20, verbose_name='主机分组类型'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='database_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='数据库类型'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='resource_type',
            field=models.CharField(choices=[('host', '主机资源'), ('database', '数据库')], default='host', max_length=20, verbose_name='资源类型'),
        ),
        migrations.CreateModel(
            name='NetworkProxyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='网路代理名称')),
                ('linux_ip', models.CharField(blank=True, max_length=150, null=True, verbose_name='Linux IP地址')),
                ('linux_port', models.IntegerField(blank=True, default=22, null=True, verbose_name='Linux端口')),
                ('linux_login_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Linux登录名')),
                ('linux_login_password', models.CharField(blank=True, max_length=500, null=True, verbose_name='Linux密码')),
                ('windows_ip', models.CharField(blank=True, max_length=150, null=True, verbose_name='Windows IP地址')),
                ('windows_port', models.IntegerField(blank=True, default=22, null=True, verbose_name='Windows端口')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='网路代理描述')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bastion.UserInfo', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '网络代理',
                'verbose_name_plural': '网络代理',
                'db_table': 'network_proxy',
            },
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='network_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_proxy', to='bastion.NetworkProxyModel'),
        ),
    ]
