# Generated by Django 2.2.6 on 2020-10-09 10:25

from django.db import migrations
from bastion.utils.init_default_group import init_default_group


def run_init(apps, schema_editor):
    init_default_group()


class Migration(migrations.Migration):

    dependencies = [
        ('bastion', '0008_auto_20211126_1238'),
    ]

    operations = [
        migrations.RunPython(run_init)
    ]